### PR TITLE
build: Add linux-aarch64 support

### PR DESCRIPTION
**Pull request by martin-g**
This is continuation of https://github.com/conda-forge/vina-feedstock/pull/15.
#15 fails to build Vina on PPC64LE at TravisCI. This PR removes PPC64LE from the build matrix. It could be re-added later by someone who has more experience with it.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please ping team

**Comment by martin-g** [comment]
@conda--forge/core Could someone help here with the review and merge of this PR ? Thank you in advance!

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge/core Could someone help with a review and merge of this PR ? Thank you!

**Review by simonbray — APPROVED** [review]

**Comment by simonbray** [comment]
Thank you!

**Comment by martin-g** [comment]
Thank you for merging, @simonbray !

**Pull request merged**
